version: 2
jobs:
  build:
    docker:
    
      - image: circleci/node:6

      

    working_directory: ~/circleci-c-se

    steps:
      - checkout

      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            
            - v1-dependencies-

      - run: npx install
      - run: npx install --save-dev jest

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      
      - run: npx test