version: 2
jobs:
  build:
    docker:
    
      - image: circleci/node:12.4.0

      

    working_directory: ~/circleci-c-se

    steps:
      - checkout
      - run: npm install
      - run: npm test